
import { ComboBox, Slider, CheckBox } from "std-widgets.slint";

struct Layer {
    fgtiles: bool,
    bgtiles: bool,
    entities: bool,
    fgdecals: bool,
    bgdecals: bool,
}

export struct RenderSettings {
    width: float,
    only-render-visited: bool,
    color-mode: string,
    anti-alias: bool,
    layer: Layer,
}

export global Render {
    callback render(RenderSettings);
    in property <RenderSettings> render-settings: {
        width: 2,
        only-render-visited: true,
        color-mode: "State",
        anti-alias: true,
        layer: { fgtiles: true, bgtiles: true, entities: true, fgdecals: true, bgdecals: true },
    };
    in property <string> render-status: "";
}

export component RenderSettingsTable inherits GridLayout {

    spacing: 8px;
    Row {
        Text {
            font-size: 18pt;
            text: "Render Settings";
        }
    }

    Row {
        color-row := Text {
            vertical-alignment: center;
            width: 30%;
            text: "Color";
        }

        ComboBox {
            current-value: Render.render-settings.color-mode;
            // Keep in sync with render()
            model: ["State", "Random", "Gradient", "Red"];
            selected(val) => {
                Render.render-settings.color-mode = val;
            }
        }
    }

    Row {
        Text {
            vertical-alignment: center;
            text: "Line Width";
        }

        HorizontalLayout {
            spacing: 8px;
            slider := Slider {
                value: Render.render-settings.width;
                minimum: 1.0;
                maximum: 20.0;

                changed(val) => {
                    Render.render-settings.width = val;
                }
            }

            Text {
                text: Math.round(slider.value * 100) / 100;
            }
        }
    }

    Row {
        Text {
            vertical-alignment: center;
            text: "Only include visited rooms";
        }

        HorizontalLayout {
            alignment: LayoutAlignment.start;
            CheckBox {
                checked: Render.render-settings.only-render-visited;
                toggled => {
                    Render.render-settings.only-render-visited = self.checked;
                }
            }
        }
    }

    Row {
        Text {
            vertical-alignment: center;
            text: "Line Antialiasing";
        }

        HorizontalLayout {
            alignment: LayoutAlignment.start;
            CheckBox {
                checked: Render.render-settings.anti-alias;
                toggled => {
                    Render.render-settings.anti-alias = self.checked;
                }
            }
        }
    }

    Row {
        Text {
            vertical-alignment: center;
            text: "Layers";
        }

        HorizontalLayout {
            alignment: space-between;
            CheckBox {
                text: "Tiles (FG)";
                checked: Render.render-settings.layer.fgtiles;
                toggled => {
                    Render.render-settings.layer.fgtiles = self.checked;
                }
            }

            CheckBox {
                text: "Tiles (BG)";
                checked: Render.render-settings.layer.bgtiles;
                toggled => {
                    Render.render-settings.layer.bgtiles = self.checked;
                }
            }

            CheckBox {
                text: "Entities";
                checked: Render.render-settings.layer.entities;
                toggled => {
                    Render.render-settings.layer.entities = self.checked;
                }
            }

            CheckBox {
                text: "Decals (FG)";
                checked: Render.render-settings.layer.fgdecals;
                toggled => {
                    Render.render-settings.layer.fgdecals = self.checked;
                }
            }

            CheckBox {
                text: "Decals (BG)";
                checked: Render.render-settings.layer.bgdecals;
                toggled => {
                    Render.render-settings.layer.bgdecals = self.checked;
                }
            }
        }
    }
}
