[package]
name = "tbd"
version = "0.1.0"
edition = "2021"

[dependencies]
celesteloader = { version = "0.1.0", path = "../celestetools/crates/celesteloader" }
celesterender = { version = "0.1.0", path = "../celestetools/crates/celesterender" }
annotate_celeste_map = { version = "0.1.0", path = "../celestetools/crates/annotate_celeste_map" }
celestedebugrc = { version = "0.1.0", path = "../celestetools/crates/celestedebugrc" }

slint = { version = "1.5", default-features = false, features = ["std", "compat-1-2", "backend-winit", "renderer-femtovg"] }
native-dialog = "0.7.0"
opener = "0.6.1"

anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
indexmap = "2.2"
chrono = { version = "0.4", features = [] }
notify-debouncer-full = { version = "0.3", default-features = false }

[build-dependencies]
slint-build = "1.5.0"

[profile.dev.package."*"]
opt-level = 2
